Repository ISIS3510-202410-Team33/mobile-kotlin, pull requests merged in 2024-04, with the labels that each got.

#27 GPS notification implemented
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/res/drawable/background_gradient.xml
  app/src/main/res/drawable/main_menu_scroll.xml
  app/src/main/res/drawable/main_menu_scroll2.xml
  app/src/main/res/drawable/rec1.png
  app/src/main/res/drawable/rec2.png
  app/src/main/res/drawable/university_button.xml
  app/src/main/res/layout/activity_main_menu.xml
Labels: enhancement

#29 Connectivity Scenario 5 implemented
  .idea/misc.xml
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/SplashActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/UserPreferencesViewModel.kt
  app/src/main/res/drawable/sun.gif
  app/src/main/res/drawable/sun.png
  app/src/main/res/layout/activity_main_menu.xml
Labels: Feature

#36 UI/UX for map activity improved
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/res/drawable/best_rated.png
  app/src/main/res/drawable/building_container.xml
  app/src/main/res/drawable/gps_glass.png
  app/src/main/res/drawable/university_button2.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/dialog_calification.xml
  app/src/main/res/values/elevation.xml
Labels: enhancement

#38 New MVVM ProfileActivity set up
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/model/data/Profile.kt
  app/src/main/java/com/example/ventura/ui/screens/ProfileScreen.kt
  app/src/main/java/com/example/ventura/ui/theme/Color.kt
  app/src/main/java/com/example/ventura/ui/theme/Shape.kt
  app/src/main/java/com/example/ventura/ui/theme/Theme.kt
  app/src/main/java/com/example/ventura/ui/theme/Typography.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/NewProfileActivity.kt
  app/src/main/java/com/example/ventura/view/ProfileActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/ProfileViewModel.kt
  app/src/main/res/drawable/john_doe_profile_picture.jpg
  gradle/libs.versions.toml
Labels: enhancement

#42 NewProfileActivity UI textbox failed update solved
  app/src/main/java/com/example/ventura/ui/screens/ProfileScreen.kt
  app/src/main/java/com/example/ventura/viewmodel/ProfileViewModel.kt
Labels: bug

#40 Exclusion of .idea folder
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/appInsightsSettings.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: bug

#55 Feature/campus locations fetching offline scenario
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/edificios.json
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/ProfileActivity.kt
  app/src/main/java/com/example/ventura/view/SignUpActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/DataViewModel.kt
  app/src/main/res/drawable/cloud.png
  app/src/main/res/drawable/cloud_with_rain.png
  app/src/main/res/drawable/notification_icon_2.png
  app/src/main/res/drawable/rounded_corners.xml
  app/src/main/res/drawable/rounded_corners_rain.xml
  app/src/main/res/drawable/rounded_corners_sun.xml
  app/src/main/res/drawable/sun_behind_cloud.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_signup.xml
  gradle/libs.versions.toml
Labels: Feature

#58 Thread based weather retrieval
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/WeatherViewModel.kt
  app/src/main/res/drawable/error.png
  gradle/libs.versions.toml
Labels: enhancement

#61 Fixes the main menu activity callback errors.
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/view/ProfileActivity.kt
Labels: bug

#62 Enhancement/refactored to follow mvvm pattern
  app/src/main/java/com/example/ventura/model/CampusLocationsModel.kt
  app/src/main/java/com/example/ventura/model/LoginModel.kt
  app/src/main/java/com/example/ventura/model/SignUpModel.kt
  app/src/main/java/com/example/ventura/repository/FirestoreRepository.kt
  app/src/main/java/com/example/ventura/repository/WeatherResponse.kt
  app/src/main/java/com/example/ventura/service/WeatherService.kt
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/SignUpActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/CampusLocationsViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/DataViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/SignUpViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/WeatherViewModel.kt
  app/src/main/res/drawable/university_button3.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_menu.xml
Labels: enhancement

#66 Enhancement/refactored the remaining viewmodels to follow mvvm pattern
  app/src/main/java/com/example/ventura/model/CampusLocationsModel.kt
  app/src/main/java/com/example/ventura/model/RatingModel.kt
  app/src/main/java/com/example/ventura/model/UserPreferencesModel.kt
  app/src/main/java/com/example/ventura/model/WeatherModel.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/RatingViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/UserPreferencesViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/WeatherViewModel.kt
Labels: enhancement

#68 Implemented the eventual connectivity scenarios for notifications, log in and sign up
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/view/SignUpActivity.kt
  app/src/main/res/drawable/no_net.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/notifications_page.xml
Labels: Feature

#71 Updated and improved the ui/ux for log in and sign up
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/res/drawable/ventura_tittle.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/login_no_internet.xml
Labels: Feature

#69 Theme options added
  app/src/main/java/com/example/ventura/model/ProfileModel.kt
  app/src/main/java/com/example/ventura/model/data/Brightness.kt
  app/src/main/java/com/example/ventura/model/data/Profile.kt
  app/src/main/java/com/example/ventura/model/data/Theme.kt
  app/src/main/java/com/example/ventura/model/service/ProfileService.kt
  app/src/main/java/com/example/ventura/ui/screens/ProfileScreen.kt
  app/src/main/java/com/example/ventura/ui/theme/Color.kt
  app/src/main/java/com/example/ventura/ui/theme/Shape.kt
  app/src/main/java/com/example/ventura/ui/theme/ThemeScreen.kt
  app/src/main/java/com/example/ventura/ui/theme/Typography.kt
  app/src/main/java/com/example/ventura/view/BrightnessManager.kt
  app/src/main/java/com/example/ventura/view/LightSensitiveThemeActivity.kt
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/NewProfileActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/ThemeViewModel.kt
  app/src/main/res/font/abeezee_italic.ttf
  app/src/main/res/font/abeezee_regular.ttf
  app/src/main/res/font/poppins_light.ttf
  app/src/main/res/font/poppins_medium.ttf
  app/src/main/res/font/poppins_regular.ttf
  app/src/main/res/font/poppins_semibold.ttf
Labels: enhancement

#72 Feature/maps page offline scenario
  app/src/main/java/com/example/ventura/model/CampusLocationsModel.kt
  app/src/main/java/com/example/ventura/model/RatingModel.kt
  app/src/main/java/com/example/ventura/model/UserPreferencesModel.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/view/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/RatingViewModel.kt
  app/src/main/res/drawable/rounded_corners_cloud.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/login_no_internet.xml
Labels: Feature

#74 Fixed map activity showing duplicated campus locations after requesting an update
  app/src/main/java/com/example/ventura/model/CampusLocationsModel.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
Labels: bug

#77 Fixed the ui and ux for uniandes banner button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MejorEdificioAdapter.kt
  app/src/main/java/com/example/ventura/view/NotificationsActivity.kt
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/notifications_page.xml
Labels: Feature

#79 BQ 3 (Sprint 3) - Step and calorie counters #78
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/StepCounterApplication.kt
  app/src/main/java/com/example/ventura/model/dao/StepCountDao.kt
  app/src/main/java/com/example/ventura/model/data/StepCount.kt
  app/src/main/java/com/example/ventura/model/data/StepCountUi.kt
  app/src/main/java/com/example/ventura/model/databases/StepCountDatabase.kt
  app/src/main/java/com/example/ventura/repository/StepCounterRepository.kt
  app/src/main/java/com/example/ventura/ui/screens/ProfileScreen.kt
  app/src/main/java/com/example/ventura/ui/theme/Typography.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/NewProfileActivity.kt
  app/src/main/java/com/example/ventura/view/StepCounterActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/StepCounterViewModel.kt
  build.gradle.kts
Labels: Feature
