Repository ISIS3510-202410-Team33/mobile-kotlin, pull requests merged in 2024-05, with the labels that each got.

#83 Added documentation for some strategies
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/model/UserPreferencesModel.kt
  app/src/main/java/com/example/ventura/ui/activity/LoginActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/SplashActivity.kt
  app/src/main/java/com/example/ventura/ui/fragment/ImageDialogFragment.kt
  app/src/main/res/layout/fragment_image_dialog.xml
Labels: documentation

#85 Sensor management fixed
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/PermanentSensorsApplication.kt
  app/src/main/java/com/example/ventura/StepCounterApplication.kt
  app/src/main/java/com/example/ventura/data/ui/ThemeUiState.kt
  app/src/main/java/com/example/ventura/model/SensorModel.kt
  app/src/main/java/com/example/ventura/repository/LightSensitiveThemeRepository.kt
  app/src/main/java/com/example/ventura/repository/StepCounterRepository.kt
  app/src/main/java/com/example/ventura/repository/ThemeRepository.kt
  app/src/main/java/com/example/ventura/ui/activity/LightSensitiveThemeActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/NewProfileActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/StepCounterActivity.kt
  app/src/main/java/com/example/ventura/ui/screen/ProfileScreen.kt
  app/src/main/java/com/example/ventura/ui/theme/ThemeScreen.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/StepCounterViewModel.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/ThemeViewModel.kt
  app/src/main/java/com/example/ventura/utils/SensorService.kt
  gradle/libs.versions.toml
Labels: bug

#87 Fully Implemented campus images feature (new)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/ui/activity/CampusImagesActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/NotificationsActivity.kt
  app/src/main/java/com/example/ventura/ui/adapter/MejorEdificioAdapter.kt
  app/src/main/res/drawable/loading_placeholder.gif
  app/src/main/res/layout/campus_images.xml
  app/src/main/res/layout/image_item.xml
Labels: Feature

#89 NetworkHandler to check internet connection
  app/src/main/java/com/example/ventura/PermanentSensorsApplication.kt
  app/src/main/java/com/example/ventura/model/SensorModel.kt
  app/src/main/java/com/example/ventura/model/WeatherModel.kt
  app/src/main/java/com/example/ventura/repository/LightSensitiveThemeRepository.kt
  app/src/main/java/com/example/ventura/repository/ProfileRemote.kt
  app/src/main/java/com/example/ventura/repository/StepCountDatabase.kt
  app/src/main/java/com/example/ventura/repository/StepCounterRepository.kt
  app/src/main/java/com/example/ventura/repository/ThemeRepository.kt
  app/src/main/java/com/example/ventura/ui/activity/CampusImagesActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/NewProfileActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/StepCounterActivity.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/StepCounterViewModel.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/ThemeViewModel.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/WeatherViewModel.kt
  app/src/main/java/com/example/ventura/utils/BrightnessManager.kt
  app/src/main/java/com/example/ventura/utils/NetworkHandler.kt
  app/src/main/java/com/example/ventura/utils/SensorService.kt
Labels: bug

#92 Enhancement/reconnection scenario user experience enhancement
  app/src/main/java/com/example/ventura/model/CampusLocationsModel.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MapActivity.kt
  app/src/main/res/drawable/load3.gif
Labels: enhancement

#95 Implemented the buttons for the new features and the templates
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/ui/activity/CoursesActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/res/drawable/calendar.png
  app/src/main/res/drawable/note.png
  app/src/main/res/drawable/notebook.png
  app/src/main/res/drawable/notebook_icon.png
  app/src/main/res/drawable/search_bar.xml
  app/src/main/res/drawable/sub_menu_1.xml
  app/src/main/res/layout/activity_courses.xml
  app/src/main/res/layout/activity_main_menu.xml
Labels: Feature

#99 Implemented new courses feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/repository/CourseRepository.kt
  app/src/main/java/com/example/ventura/ui/activity/AddCourseActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/CoursesActivity.kt
  app/src/main/java/com/example/ventura/ui/adapter/CoursesAdapter.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/CourseViewModel.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/CourseViewModelFactory.kt
  app/src/main/res/drawable/trash_icon.png
  app/src/main/res/layout/activity_add_course.xml
  app/src/main/res/layout/activity_courses.xml
  app/src/main/res/layout/item_course.xml
  app/src/main/res/layout/login_no_internet.xml
Labels: Feature

#100 schedule activity created + calendar implemented
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/PermanentSensorsApplication.kt
  app/src/main/java/com/example/ventura/ui/activity/AgendaMainActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/utils/SensorService.kt
  app/src/main/res/drawable/selected_date_bg.xml
  app/src/main/res/layout/activity_main_cal.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/calendar_day_layout.xml
  app/src/main/res/layout/calendar_day_title_text.xml
  app/src/main/res/layout/calendar_day_titles_container.xml
Labels: Feature

#103 Feature/schedule activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/data/Converters.kt
  app/src/main/java/com/example/ventura/data/FirebaseTaskDao.kt
  app/src/main/java/com/example/ventura/data/TaskDao.kt
  app/src/main/java/com/example/ventura/data/TaskDatabase.kt
  app/src/main/java/com/example/ventura/model/DatabaseHelper.kt
  app/src/main/java/com/example/ventura/model/Task.kt
  app/src/main/java/com/example/ventura/repository/TasksRepository.kt
  app/src/main/java/com/example/ventura/ui/activity/AgendaMainActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/ui/activity/NewTaskActivity.kt
  app/src/main/java/com/example/ventura/ui/adapter/TaskAdapter.kt
  app/src/main/java/com/example/ventura/ui/viewmodel/TasksViewModel.kt
  app/src/main/res/layout/activity_main_cal.xml
  app/src/main/res/layout/activity_new_task.xml
  app/src/main/res/layout/task_item.xml
  app/src/main/res/layout/task_list_item.xml
Labels: Feature
