Repository ISIS3510-202410-Team33/mobile-kotlin, pull requests merged in 2024-03, with the labels that each got.

#9 MVVM fixed + LoginActivity and SplashActivity implemented
  .gitignore
  .idea/.gitignore
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/ventura/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/ui/theme/Color.kt
  app/src/main/java/com/example/ventura/ui/theme/Theme.kt
  app/src/main/java/com/example/ventura/ui/theme/Type.kt
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/SplashActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/DataViewModel.kt
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/goose.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/neckgoose.png
  app/src/main/res/font/lato_light.ttf
  app/src/main/res/font/lato_thin.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/ventura/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: Setup

#10 Main manu
  .idea/.name
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/model/WeatherResponse.kt
  app/src/main/java/com/example/ventura/service/WeatherService.kt
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/DataViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/WeatherViewModel.kt
  app/src/main/res/drawable/duck.png
  app/src/main/res/drawable/grey_wallpaper.xml
  app/src/main/res/drawable/weather_info_background.xml
  app/src/main/res/layout/activity_main_menu.xml
  gradle/libs.versions.toml
Labels: Feature

#13 Time travel estimations developed and mobiliy constraints
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/fragments/HomeFragment.kt
  app/src/main/java/com/example/ventura/fragments/MapFragment.kt
  app/src/main/java/com/example/ventura/fragments/SettingFragment.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: Feature

#16 refactor login to mmv pattern
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/SignUpActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/ventura/viewmodel/SignUpViewModel.kt
  app/src/main/res/layout/activity_main_menu.xml
Labels: enhancement

#18 User Preferences saved on firestore: implemented
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/UserPreferencesViewModel.kt
Labels: Feature

#19 Recomended location based on user preferences and history
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/UserPreferencesViewModel.kt
  app/src/main/res/layout/activity_map.xml
Labels: Feature

#20 Crashlytics enabled with basic feature distinction
  .idea/appInsightsSettings.xml
  app/build.gradle.kts
  app/src/main/java/com/example/ventura/model/analytics/FeatureCrashHandler.kt
  app/src/main/java/com/example/ventura/view/LoginActivity.kt
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/SignUpActivity.kt
  app/src/main/java/com/example/ventura/view/SplashActivity.kt
  build.gradle.kts
Labels: Analytics, Feature

#21 Feature/weather warning #4
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/java/com/example/ventura/view/ProfileActivity.kt
  app/src/main/res/drawable/cloud.png
  app/src/main/res/drawable/profile_image.png
  app/src/main/res/drawable/rain.png
  app/src/main/res/drawable/sun.png
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/activity_profile.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: Feature

#22 Feature/bq 4 #5
  app/src/main/java/com/example/ventura/view/MapActivity.kt
  app/src/main/java/com/example/ventura/viewmodel/RatingViewModel.kt
  app/src/main/res/layout/activity_map.xml
  app/src/main/res/layout/dialog_calification.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#23 Style update + final test
  app/src/main/java/com/example/ventura/view/MainMenuActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: enhancement
